### PR TITLE
YouTube shorts.

### PR DESCRIPTION
**Pull request by KoshikKumar17**
For YouTube shorts thumbnail link

### CODE REVIEW

**Comment by FayasNoushad** [comment]
```py
# if video is a link
if "/" in video:
    id = video.split("/")[-1]

# "youtu.be" link format
if "?" in id:
    id = id.split("?")[0]
```

Actually, shorts are supported with these two statements (process)

**Review by fayasnoushad — COMMENTED** [review]
```py
# if video is a link
if "/" in video:
    id = video.split("/")[-1]

# "youtu.be" link format
if "?" in id:
    id = id.split("?")[0]
```

Actually, shorts are supported with these two statements (process)

**Comment by KoshikKumar17** [comment]
Ok

**Comment by fayasnoushad** [comment]
Thanks for your contribution.

**Pull request closed without merging**
